---
title: "Rethinking Felony Disenfranchisement: The Case of New York City and Miami"
author: "Kevin Morris"
date: "April 22, 2019"
output: pdf_document
bibliography: "test.bib"
link-citations: yes
---

<!-- --- -->
<!-- title: "Rethinking Felony Disenfranchisement: The Case of New York City and Miami" -->

<!-- # to produce blinded version set to 1 -->
<!-- blinded: 0 -->

<!-- authors: -->
<!-- - name: Kevin Morris -->
<!--   thanks: The author gratefully acknowledges Jacob Faber and Jeff Manza for their advisement of this project. He would also like to thank colleagues at the Brennan Center for Justice for their insights into this project. -->
<!--   affiliation: Robert F. Wagner School of Public Service, New York University -->

<!-- keywords: -->
<!-- - 3 to 6 keywords -->
<!-- - that do not appear in the title -->

<!-- abstract: | -->
<!--   The text of your abstract.  200 or fewer words. -->

<!-- output: rticles::asa_article -->
<!-- --- -->

```{r, echo = F}
knitr::opts_knit$set(root.dir = "../..")
```

"There is no Negro problem. There is no Southern problem. There is no Northern problem. There is only an American problem"

-*Lyndon Johnson, March 15, 1965*

#Introduction

Felony disenfranchisement has received much attention over the past few years. This is true in both the academic world (where researchers have dug into the political ramifications in such races as the 2000 presidential election) and in the political world as states such as Florida and Louisiana have gradually moved to dismantle their systems of disenfranchisement. Throughout this process, however, many researchers have focused on the *individual* effects of felony disenfranchisement. They have examined the effect of disenfranchisement on the political participation of individuals, including after they are no longer disenfranchised, but have generally neglected to examine the intersection of spatially concentrated policing and incarceration patterns with the political effects of disenfranchisement. This paper seeks to increase our understanding of the spatial implications of felony disenfranchisement by examining the character of disenfranchisement in New York City and Miami-Dade County in Florida.

This paper also seeks to complicate the narratives surrounding the end of felony disenfranchisement. Although advocates are correct to push for an end to disenfranchisement, a change to the political system may not be sufficient to reincorporate the voices of formerly incarcerated individuals into the democratic process. In addition to laying out the spatial implications of felony disenfranchisement in two major American cities, this paper also explores the impact of two different policies intended to dismantle the disenfranchisement program. Specifically, I investigate the effect of Executive Order 181 (which ended the disenfranchisement of parolees in New York State) and  Amendment 4 (which restored the voting rights of Floridians who had completed all terms of their sentences). The effects of these policies make clear that, while the end of felony disenfranchisement is necessary, active steps must be taken to reincorporate the formerly disenfranchised.

#Background of Felony Disenfranchisement in the United States

In all but two states (Maine and Vermont), felony disenfranchisement laws ensure that American citizens convicted of felony offenses lose the right to vote for at least some period of time. In some states, such as Oregon and Massachusetts, individuals lose that right only for the period in which they are actively incarcerated. In other states, notably Kentucky and Iowa, felony convictions result in lifelong disenfranchisement unless a returned citizen receives an individual pardon from the state's governor [@bcj_laws]. This variation in laws flows directly from language in the Fourteenth Amendment which allows states to revoke individuals' voting rights "for participation in rebellion, or other crime." The definition of "other crime," left so vague in the Constitution, is now generally used by states to encompass any felony offense at all. The Supreme Court, in cases such as *Richardson v. Ramirez*, has upheld states' right to do just that. Collectively, these laws disenfranchise as many as ```r 6.1 - 1.4``` million American citizens. Of these, the majority are no longer incarcerated, but are living and working in their communities [@sentencing_2016].^[The figures reported in @sentencing_2016 have been adjusted to reflect the impact of Amendment 4 in Florida.]

In any discussion of felony disenfranchisement in the United States, it is imperative to acknowledge the central role played by race and white supremacy. As Traci Burch has explained, "If policies restricting the voting rights of offenders disparately affect one racial group or party, it is because such policies were intended to" [@Burch2010]. The historical record is undeniable. Previous research established that the presence of nonwhite potential voters is associated with the implementation of felony disenfranchisement policies and that these policies were often adopted during Jim Crow to reduce the political power of Black Americans [@Behrens2003]. In Florida felony disenfranchisement was added to the state constitution in 1868. Afterwards, a lawmaker boasted that the effort had been made in order to prevent Florida from being "niggerized" [@florida_1868].

The racial imbalance of felony disenfranchisement laws are not, of course, confined to the 19th century. Although the Voting Rights Act of 1965 did much to improve access to the ballot box for minorities, it did nothing to undermine the explicitly racialized system of disenfranchisement. Indeed, as the United States has vastly increased the reach of the carceral system in the post-Civil Rights era, the implications of felony disenfranchisement have only grown. In XX states, as many as 25 percent of Black men are currently disenfranchised. 

In the aftermath of the 2000 presidential election, academic interest in the political implications of felony disenfranchisement was stirred thanks to a paper from Christopher Uggen and Jeff Manza [-@Uggen2002]. George W. Bush's margin of victory in Florida in 2000 was famously just 537 votes. In their 2002 paper, Uggen and Manza estimate the likely partisan composition of the disenfranchised population with felony convictions in their past. They estimate that, if this group had been allowed to vote, they would have supported Al Gore. Their enfranchisement, Uggen and Manza posit, would have tipped the presidential contest and resulted in the election of Al Gore.


#Spatial Effects of Concentrated Policing and Incarceration

Previous literature has called attention to the racially disparate impacts of felony disenfranchisement in the United States. It has often failed, however, to explore the ways in which the disenfranchisement of individuals leads to a loss of political power for community members

##concentrated policing
\newpage
#References